import Head from "next/head";
import styles from "../styles/Recommend.module.css";
import React from "react";
import SearchBar from "../components/home/SearchBar";

export default class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  handleCheckBox = (e) => {
    this.setState({ [e.target.name]: !this.state[e.target.name] });
  };

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Recommendations based on</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.mainHead}>
          <div className={styles.centralContainer}>
            <h1 className={styles.title}>
              If you liked Demian sdaijifduajasdfif, you may like these as well
            </h1>
            <SearchBar
              include_author={this.state.include_author}
              include_saga={this.state.include_saga}
            />
            <form className={styles.filters}>
              <label className={styles.filterText}>
                <input
                  className={styles.filterCheckbox}
                  name="include_saga"
                  type="checkbox"
                  checked={this.state.include_saga}
                  onChange={this.handleCheckBox}
                />
                Include books from the same saga
              </label>
              <br />
              {/* <label className={styles.filterText}>
              <input
              className={styles.filterCheckbox}
              name="include_author"
              type="checkbox"
              checked={this.state.include_author}
              onChange={this.handleCheckBox}
              />
              Include books from the same author
            </label> */}
            </form>
          </div>
        </div>
        <main className={styles.main}></main>
      </div>
    );
  }
}
